
```{r}
cor_matrix <- matrix(c(1, 0.5498499, 0.4359084,
                       0.5498499, 1, 0.4655891,
                       0.4359084, 0.4655891, 1), 
                     nrow = 3, byrow = TRUE)
rownames(cor_matrix) <- colnames(cor_matrix) <- c("LasR", "RhlR", "MvfR")

library(ellipse)
library(gplots)
library(RColorBrewer)
my_colors <- brewer.pal(5, "Spectral")
my_colors <- colorRampPalette(my_colors)(100)
pdf("/Users/lubeifang/Desktop/co_3iModulon.pdf",width=4,height=4)
plotcorr(cor_matrix , col=my_colors[cor_matrix*50+50] , mar=c(1,1,1,1),
         numbers = F ,
         type = c("full"), diag = T)
dev.off()
```



# activity bar plot
```{r}

library(ggplot2)

data <- data.frame(
  Mutant = c("ΔrpoN-2", "ΔrpoN-1", "ΔPA2229/30-2", "ΔPA2229/30-1", 
             "ΔlasR-1", "ΔlasR-2", "ΔlasR-3", "ΔlasR-4", "ΔlasR-5"),
  Activity = c(-23.78, -23.25, -18.12, -17.84, -17.76, -17.63, -17.53, -17.35, -16.26),
  Bin = c("Bin1", "Bin1", "Bin2", "Bin2", "Bin2", "Bin2", "Bin2", "Bin2", "Bin2")
)


ggplot(data, aes(x = Mutant, y = Activity, fill = Bin)) +
  geom_bar(stat = "identity", width = 0.7) + 
  labs(
    title = "Activity Values of Mutants",
    x = "Mutant",
    y = "Activity Value"
  ) +
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  ) +
  scale_fill_manual(values = c("Bin1" = "skyblue", "Bin2" = "orange"))




data <- data.frame(
  sample = c("Δ2430-2", "Δ2430-1", "ΔrpoN-2", "ΔrpoN-1", "ΔPA2229/30-2", "ΔPA2229/30-1", 
             "ΔlasR-1", "ΔlasR-2", "ΔlasR-3", "ΔlasR-4", "ΔlasR-5",
             "ΔmvfR-2", "ΔmvfR-1", "PA4852-2", "PA4852-1",
             "ΔPA4952-1", "ΔPA4952-2", "ΔrhlR-2", "ΔrhlR-1"),
  modu = c(rep("LasR", 11), rep("MvfR", 4), rep("RhlR", 4)),
  activity = c(-24.00, -22.33, -23.78, -23.25, -18.12, -17.84, -17.76, -17.63, -17.53, -17.35, -16.26,
               -22.95, -22.71, -19.83, -18.96,
               -27.08, -25.84, -20.65, -20.28),
  activity_bin = c(rep("Bin1", 4), rep("Bin2", 7), rep("Bin1", 2), rep("Bin2", 2), 
                   rep("Bin1", 2), rep("Bin2", 2))
)

p1 <- ggplot(data[data$modu == "LasR",], aes(x = sample, y = activity, fill = activity_bin)) +
  geom_bar(stat = "identity", width = 0.7) + 
  # facet_wrap(~modu, ncol = 1, scales = "free_y") + 
  labs(
    title = "Activity Values by Modu",
    x = "Sample",
    y = "Activity Value"
  ) +
  theme_classic() + 
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1), 
    strip.text = element_text(size = 12, face = "bold") 
  ) +
  scale_fill_manual(values = c("Bin1" = "skyblue", "Bin2" = "orange")) 
p2 <- ggplot(data[data$modu == "MvfR",], aes(x = sample, y = activity, fill = activity_bin)) +
  geom_bar(stat = "identity", width = 0.7) +
  # facet_wrap(~modu, ncol = 1, scales = "free_y") + 
  labs(
    title = "Activity Values by Modu",
    x = "Sample",
    y = "Activity Value"
  ) +
  theme_classic() + 
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1), 
    strip.text = element_text(size = 12, face = "bold") 
  ) +
  scale_fill_manual(values = c("Bin1" = "skyblue", "Bin2" = "orange"))

p3 <- ggplot(data[data$modu == "RhlR",], aes(x = sample, y = activity, fill = activity_bin)) +
  geom_bar(stat = "identity", width = 0.7) +
  labs(
    title = "Activity Values by Modu",
    x = "Sample",
    y = "Activity Value"
  ) +
  theme_classic() + 
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1), 
    strip.text = element_text(size = 12, face = "bold") 
  ) +
  scale_fill_manual(values = c("Bin1" = "skyblue", "Bin2" = "orange")) 
p <- p1/p2/p3
ggsave("/Users/lubeifang/Desktop/3iModulon_bar.pdf",p,width=6,height=10)
```


# HP mutant condition & iModulon activity

```{R}

tmphptocondition <- read.csv("/Users/lubeifang/Desktop/PA_HP/Figures/F5_ICA/bin_hpcondition_modu.csv")
tmphptocondition %>%filter(size>5)%>%
  ggplot(aes(x=bin6, y=bin1,size=size)) +
  geom_point(alpha=0.6, shape=21,fill='#bf79b0') +
  geom_text_repel(aes(label=ifelse(size>=10&(bin1>=8|bin6>=8), hpid, "")), vjust=-0.5, size=3) +
  geom_abline(intercept = 0, slope = 1, color = "gray",linetype = "dashed", linewidth = 1) +
  scale_size(range = c(0.5, 10)) +
  theme_bw()+
  theme(legend.position="bottom") +
  ylab("Bin1") +
  xlab("Bin6")
ggsave('/Users/lubeifang/Desktop/bin_hpcondition_modu.pdf',height = 5.3,width = 5)

## density plot
ggplot(tmphptocondition) +
  geom_density( aes(x=n_pos),fill="#f7c264", alpha=0.7) +
  geom_density( aes(x=n_neg),fill="lightblue", alpha=0.7) +
  labs(
    title = "",
    x = "Count",
    y = "Density"
  ) +
  theme_bw()
ggsave('/Users/lubeifang/Desktop/bin_hpcondition_modu_density.pdf',height = 4,width = 5)
```

```{R}
library(reshape2)
library(tidyverse)
library(ggrepel)
activity <- read.csv("/Users/lubeifang/Desktop/PA_HP/Figures/F5_ICA/hptmp2.csv", row.names = 1) %>%
  distinct(hpid, modu, .keep_all = TRUE)
activity%>%distinct(modu,hpid,.keep_all = TRUE)%>%filter(lower_out | higher_out)%>%dim()
activity$label <- ifelse(activity$activity >0, "positive","negative" )

length(unique(activity$modu))
length(unique(activity$sample))

# calculate mean
activity_mean <- activity %>%
  group_by(modu, label) %>%
  summarise(mean_activity = mean(activity)) %>%
   pivot_wider(
    names_from = label,       
    values_from = mean_activity
  )


pval <- read.csv("/Users/lubeifang/Desktop/PA_HP/Figures/F5_ICA/bubblepink(1).csv",row.names = 1)
activity_mean <- merge(activity_mean, pval, by="modu")
ggplot(activity_mean,aes(x=-negative, y=positive, fill = -log10(wilcox_p), size=n_pos/n_neg)) +
  geom_point(shape=21, stroke=1) +
  geom_text_repel(aes(label=ifelse(-log10(wilcox_p) > 10, modu, "")), vjust=-0.5, size=3) +
  labs(
    title = "Mean Activity Difference by Modu",
    x = "Mean activity of negative condition",
    y = "Mean Activity of positive condition"
  ) +
  theme_bw() +
  # theme(
  #   axis.text.x = element_text(angle = 45, hjust = 1)
  # ) +
  scale_fill_gradient(low = "pink", high = "lightblue") +
  geom_abline(intercept = 0, slope = 1, color = "grey", linetype = "dashed", size = 1) +
  xlim(0,9) +
  ylim(0,9)

ggsave("/Users/lubeifang/Desktop/HP_mutant_modu_activity.pdf",width=5.3,height=4)
```

```{r}
sig <- activity %>% filter(lower_out | higher_out)
length(unique(sig$modu))
length(unique(sig$hpid))
length(unique(activity$hpid))
sig %>%
  ggplot(aes(x=modu, y=activity, color=label)) +
  geom_jitter(width=0.2, alpha=0.6) +
  geom_boxplot(outlier.shape = NA, alpha=0.4, position=position_dodge(0.75)) +
  labs(
    title = "Activity Values by Modu",
    x = "Modu",
    y = "Activity Value"
  ) +
  theme_classic() + # 使用简洁主题
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1) 
  ) +
  scale_color_manual(values = c("positive" = "orange", "negative" = "skyblue")) 

ggsave("/Users/lubeifang/Desktop/HP_mutant_modu_activity_box.pdf",width=7,height=4)

hpid_count <- sig %>%
  group_by(hpid,label) %>%
  summarise(count = n()) %>%
  pivot_wider(
    names_from = label,
    values_from = count,
    values_fill = 0
  ) 
ggplot(hpid_count,aes(x=positive, y=negative,size=positive + negative)) +
  geom_point(alpha=0.6, shape=21,fill='#bf79b0') +
  geom_text_repel(aes(label=ifelse((positive + negative)>=5&(positive>=3|negative>=3), hpid, "")), vjust=-0.5, size=3) +
  geom_abline(intercept = 0, slope = 1, color = "gray",linetype = "dashed", linewidth = 1) +
  scale_size(range = c(0.5, 10)) +
  theme_bw()+
  theme(legend.position="bottom") +
  ylab("number of repressed iModulon") +
  xlab("number of activated iModulon")
ggsave('/Users/lubeifang/Desktop/bin_hpcondition_modu.pdf',height = 5.3,width = 5)

a<-data.frame(table(sig$hpid)) %>%
  ggplot(aes(x=Freq)) +
  geom_density( fill="#f7c264", alpha=0.7)


pa0319 <- sig[sig$hpid == "PA0319",]
pa0319 %>%
  ggplot(aes(x=modu, y=activity, fill=label)) +
  geom_bar(stat = "identity",width=0.7, alpha=0.6) +
  labs(
    title = "Activity Values of PA0319 mutant by Modu",
    x = "Modu",
    y = "Activity Value"
  ) +
  theme_bw() + 
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1), 
    legend.position="none"
  ) +
  coord_flip() +
  scale_fill_manual(values = c("positive" = "orange", "negative" = "skyblue")) 

ggsave("/Users/lubeifang/Desktop/PA0319_modu_activity_bar.pdf",width=2.6,height=4)



## number
p1<-data.frame(table(sig$hpid)) %>%
  ggplot(aes(x=Freq)) +
  geom_density( fill="pink", alpha=0.7) +
  geom_boxplot(aes(y=0), width=0.1, position=position_nudge(y = -0.02), alpha=0.4) +
  theme_bw()
a<-data.frame(table(sig[sig$label == "positive",]$hpid))
b<-data.frame(table(a$Freq))
p2<-ggplot(b,aes(x=Var1, y=Freq)) +
  geom_bar(stat = 'identity', fill="#f7c264", alpha=0.7)+
  theme_bw() +
  geom_text(aes(label=Freq), vjust=-0.5)
c<-data.frame(table(sig[sig$label == "negative",]$hpid))
d<-data.frame(table(c$Freq))
p3<-ggplot(d,aes(x=Var1, y=Freq)) +
  geom_bar(stat = 'identity', fill="skyblue", alpha=0.7)+
  theme_bw()+geom_text(aes(label=Freq), vjust=-0.5)

p <- p1 + (p2 / p3)
ggsave('/Users/lubeifang/Desktop/bin_hpcondition_modu_number.pdf',p,height = 3.6,width = 8)
```


# corr
```{r}
corr <- read.csv("/Users/lubeifang/Desktop/PA_HP/Figures/F5_ICA/hpcorr56.csv", row.names = 1)
corr$label <- ifelse(corr$Corr >0, "positive","negative" )
corr_sig <- corr[abs(corr$Corr) >= 0.4,] %>%
  group_by(modulon, label) %>%
  summarise(count = n())
corr_mean <- corr[abs(corr$Corr) >= 0.4,] %>%
  group_by(modulon, label) %>%
  summarise(mean_corr = mean(Corr)) 

co <- merge(corr_sig, corr_mean, by=c("modulon","label")) %>%
   pivot_wider(
    names_from = label,
    values_from = c(count, mean_corr)) 
co[is.na(co)] <- 0
ggplot(co,aes(x=mean_corr_positive, y=-mean_corr_negative,size=count_positive + count_negative)) +
  geom_point(alpha=0.6, shape=21,fill='#95c971') +
  # geom_text_repel(aes(label=ifelse((count_positive + count_negative)>=100|(mean_corr_positive>=0.5|mean_corr_negative>=0.5), modulon, "")), vjust=-0.5, size=3) +
  geom_text_repel(aes(label=modulon, vjust=-0.5, size=5)) +
  # geom_abline(intercept = 0, slope = 1, color = "gray",linetype = "dashed", linewidth = 1) +
  scale_size(range = c(0.5, 10)) +
  theme_bw()+
  theme(legend.position="bottom") +
  ylab("average correlation score of repressed iModulon") +
  xlab("average correlation score of activated iModulon") +
  xlim (0.4,0.75) +
  ylim(0.4, 0.48)
ggsave('/Users/lubeifang/Desktop/modu_corr_bubble.pdf',height = 5.3,width = 5)

c <- corr_sig <- corr[abs(corr$Corr) >= 0.4,] %>%
  group_by(HPID, label) %>%
  summarise(count = n())
b<-data.frame(table(c[c$label == "positive",]$count))
p2<-ggplot(b,aes(x=Var1, y=Freq)) +
  geom_bar(stat = 'identity', fill="#f7c264", alpha=0.7)+
  theme_bw() +
  geom_text(aes(label=Freq), vjust=-0.5)
d<-data.frame(table(c[c$label == "negative",]$count))
p3<-ggplot(d,aes(x=Var1, y=Freq)) +
  geom_bar(stat = 'identity', fill="skyblue", alpha=0.7)+
  theme_bw()+geom_text(aes(label=Freq), vjust=-0.5)

p <- (p2 / p3)
ggsave('/Users/lubeifang/Desktop/corr_number.pdf',p,height = 3.6,width = 4)
```
