# PLOT

## HP in module
```{r}
library(ggVennDiagram)
library(ggplot2)
HP <- read.csv("/Users/lubeifang/Desktop/PA_HP/files/HP_mu.csv")
data <- read.csv("/Users/lubeifang/Desktop/PA_HP/files/HP_430_iModulon.csv")
HP_anno <- read.csv("/Users/lubeifang/Desktop/all.csv")

x = list(a=data$locus,
         b=HP_anno[HP_anno$ICA.perspective.1 != "#N/A",]$HP.genes,
         c=HP_anno[HP_anno$ICA.perspective.2 != "#N/A",]$HP.genes)
ggVennDiagram(x, category.names = c("HP embedded in Modules", "ICA perspective 1", "ICA perspective 2"),
              label = "count") +
                scale_fill_gradient(low = "white", high = "lightblue")
ggsave("/Users/lubeifang/Desktop/Module_anno_venn.pdf", width = 3, height = 3)
```

## Compare HP in differnt annotation
```{r}
library(UpSetR)
library(ggVennDiagram)
x = list(a=HP_anno[HP_anno$GO.term != "#N/A",]$HP.genes,
         b=HP_anno[HP_anno$Virulence.pathway != "#N/A",]$HP.genes,
         c=HP_anno[HP_anno$ICA.perspective.1 != "#N/A",]$HP.genes,
         d=HP_anno[HP_anno$ICA.perspective.2 != "#N/A",]$HP.genes)
# total number
length(unique(c(x$a, x$b, x$c, x$d)))
length(unique(x$d))
ggVennDiagram(x, category.names = c("GO term", "Virulence pathway", "ICA perspective 1", "ICA perspective 2"),
              label = "count") +
                scale_fill_gradient(low = "white", high = "#eb6483")
ggsave("/Users/lubeifang/Desktop/HP_anno_venn.pdf", width = 6, height = 6)

ggVennDiagram(x, category.names = c("GO term", "Virulence pathway", "ICA perspective 1", "ICA perspective 2"),
              force_upset = T) 

pdf("/Users/lubeifang/Desktop/HP_anno_upset.pdf", width = 7, height = 4)
upset(fromList(x),order.by = "freq", 
    keep.order = TRUE)
dev.off()
```

